language: node_js
cache:
  directories:
  - node_modules
node_js: stable

install:
  - npm install

script:
  - npm run build

before_deploy:
  - cd dist

deploy:
  - provider: npm
  - email: "$NPM_EMAIL"
  - api_key: "$NPM_TOKEN"
  - skip_cleanup: true
  - on:
    tags: true